### ISSUE TITLE
How to save word alignment information during predication?

### ISSUE THREAD

**Issue by patronum08** [RikVN/Neural_DRS#7]
I have tried the AllenNLP experiments and got drs.out file. I noticed that there is no word alignment (i.e. % similar [2...9]) in drs.out. How can get this?

Thanks!

'''
b1 REF x1                 % A [0...1]
b1 REF s1                 % similar [2...9]
b1 Attribute x1 s1        % similar [2...9]
b1 similar "a.01" s1      % similar [2...9]
b1 technique "n.01" x1    % technique [10...19]
b1 REF t1                 % is [20...22]
b1 EQU t1 "now"           % is [20...22]
b1 Time s2 t1             % is [20...22]
b1 time "n.08" t1         % is [20...22]
'''

**Comment by RikVN** [comment]
Sorry to get back to you so late. There are no word-alignments in the neural outputs, because the model is not trained on the alignments. Only Boxer (used for creating the gold data) gives the alignments.

**Comment by patronum08** [comment]
Got it. Many thanks!
